using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace DersaneDeneme
{
	public partial class AnaModul : DevExpress.XtraBars.Ribbon.RibbonForm
	{
		public AnaModul()
		{
			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
			// Fill the SqlDataSource asynchronously
			sqlDataSource1.FillAsync();

		}


	}
}
